export const Products = [
    {
        id: "1",
        title: "Samsung A9",
        imgSrc: "https://www.gizmochina.com/wp-content/uploads/2019/01/Samsung-Galaxy-A9-Pro-2018-569x569.jpg",
        price: 20000,
        quantity: 0,
        stock: 50,
    },
    {
        id: "2",
        title: "Samsung M31",
        imgSrc: "https://www.mobiledokan.com/wp-content/uploads/2020/02/Samsung-Galaxy-M31.jpg",
        price: 55000,
        quantity: 0,
        stock: 100,
    },
    {
        id: "3",
        title: "Samsung M21",
        imgSrc: "https://diamu.com.bd/wp-content/uploads/2020/06/Samsung-Galaxy-M21-Blue.jpg",
        price: 35000,
        quantity: 0,
        stock: 80,
    },
    {
        id: "4",
        title: "Iphone 8",
        imgSrc: "https://assets.swappie.com/swappie-product-iphone-8-gold.png",
        price: 135000,
        quantity: 0,
        stock: 80,
    },
    {
        id: "5",
        title: "Iphone 9",
        imgSrc: "https://i1.wp.com/www.mobilebd.co/wp-content/uploads/2020/04/Apple-iPhone-9-Picture-White-550x550.jpg",
        price: 150000,
        quantity: 0,
        stock: 80,
    },
];
